server:
  port: 8083
  servlet:
    context-path: /property

spring:
  application:
    name: property-service

  cloud:
    openfeign:
      lazy-attributes-resolution: true
      client:
        config:
          profile-service:
            url: http://localhost:8082/profile
  data:
    mongodb:
      uri: mongodb://admin:${MONGO_PASSWORD:${MONGO_ROOT_PASSWORD:}}@${MONGO_HOST:100.96.78.62}:${MONGO_PORT:27017}/roomie_property?authSource=admin
    redis:
      host: ${REDIS_HOST:100.96.78.62}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

  elasticsearch:
    uris: http://${ELASTICSEARCH_HOST:100.96.78.62}:${ELASTICSEARCH_PORT:9200}
    username: ${ELASTICSEARCH_USERNAME:${ELASTIC_USERNAME:elastic}}
    password: ${ELASTICSEARCH_PASSWORD:${ELASTIC_PASSWORD:}}

  cache:
    type: redis

  main:
    allow-bean-definition-overriding: true

  jackson:
    default-property-inclusion: non_null

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

property:
  max-images: 20
  image-max-size: 10MB
  google-maps-api-key: ${GOOGLE_MAPS_API_KEY:}

app:
  services:
    profile: http://localhost:8082/profile

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

---
spring:
  config:
    activate:
      on-profile: dev
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
