# docker-compose.booking-service.yml
version: '3.8'

services:
  booking-service:
    build:
      context: ./booking-service
      dockerfile: Dockerfile
    container_name: roomie-booking-service
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      - SERVER_PORT=8086
      - SPRING_APPLICATION_NAME=booking-service
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      # MySQL Configuration
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/roomie_booking
      - SPRING_DATASOURCE_USERNAME=roomie
      - SPRING_DATASOURCE_PASSWORD=roomie123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      # Redis Configuration
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_PASSWORD=roomie123
      # Kafka Configuration
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_KAFKA_CONSUMER_GROUP_ID=booking-service
      # Business Logic Configuration
      - BOOKING_TIMEOUT_MINUTES=30
      - AUTO_CANCEL_HOURS=24
      - BOOKING_CONFIRMATION_EXPIRY_HOURS=2
      # External Service URLs
      - PROPERTY_SERVICE_URL=http://property-service:8083
      - PAYMENT_SERVICE_URL=http://payment-service:8087
      - NOTIFICATION_SERVICE_URL=http://notification-service:8082
    depends_on:
      - mysql
      - redis
      - kafka
      - eureka-server
    networks:
      - roomie-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  roomie-network:
    external: true