# docker-compose.property-service.yml
version: '3.8'

services:
  property-service:
    build:
      context: ./property-service
      dockerfile: Dockerfile
    container_name: roomie-property-service
    restart: unless-stopped
    ports:
      - "8083:8083"
    environment:
      - SERVER_PORT=8083
      - SPRING_APPLICATION_NAME=property-service
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      # MySQL Configuration
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/roomie_property
      - SPRING_DATASOURCE_USERNAME=roomie
      - SPRING_DATASOURCE_PASSWORD=roomie123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      # MongoDB Configuration (for additional property data)
      - SPRING_DATA_MONGODB_URI=mongodb://admin:roomie123@mongodb:27017/roomie_property?authSource=admin
      # Neo4j Configuration (for location relationships)
      - SPRING_DATA_NEO4J_URI=bolt://neo4j:7687
      - SPRING_DATA_NEO4J_AUTHENTICATION_USERNAME=neo4j
      - SPRING_DATA_NEO4J_AUTHENTICATION_PASSWORD=roomie123
      # Redis Configuration
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_PASSWORD=roomie123
      # Elasticsearch Configuration
      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch:9200
      # Kafka Configuration
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      # External APIs
      - GOOGLE_MAPS_API_KEY=your-google-maps-api-key
      - FILE_SERVICE_URL=http://file-service:8084
      - MAX_PROPERTY_IMAGES=20
      - PROPERTY_IMAGE_MAX_SIZE=10MB
    depends_on:
      - mysql
      - mongodb
      - neo4j
      - redis
      - elasticsearch
      - kafka
      - eureka-server
    networks:
      - roomie-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  roomie-network:
    external: true