server:
  port: 8087
  servlet:
    context-path: /payment
spring:
  config:
    import:
      - optional:file:../../infra/.env[.properties]
      - optional:file:infra/.env[.properties]
  application:
    name: payment-service

  cloud:
    openfeign:
      lazy-attributes-resolution: true
      client:
        config:
          billing-service:
            url: http://localhost:8086/billing
          contract-service:
            url: http://localhost:8085/contract
          file-service:
            url: http://localhost:8088/file
          profile-service:
            url: http://localhost:8082/profile
  data:
    mongodb:
      uri: mongodb://admin:${MONGO_PASSWORD:${MONGO_ROOT_PASSWORD:}}@${MONGO_HOST:100.96.78.62}:${MONGO_PORT:27017}/roomie_payment?authSource=admin
    redis:
      host: ${REDIS_HOST:100.96.78.62}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 5000ms
  kafka:
    bootstrap-servers: ${KAFKA_HOST:100.96.78.62}:${KAFKA_PORT:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

vnpay:
  merchantCode: ${VNPAY_MERCHANT_CODE:}
  secretKey: ${VNPAY_SECRET_KEY:}
  returnUrl: ${VNPAY_RETURN_URL:http://localhost:8087/payment/webhook/vnpay}

momo:
  partnerCode: ${MOMO_PARTNER_CODE:}
  accessKey: ${MOMO_ACCESS_KEY:}
  secretKey: ${MOMO_SECRET_KEY:}
  returnUrl: ${MOMO_RETURN_URL:http://localhost:8087/payment/momo/return}
  notifyUrl: ${MOMO_NOTIFY_URL:http://localhost:8087/payment/webhook/momo}
app:
  services:
    contract: http://localhost:8085/contract
    profile: http://localhost:8082/profile
    files: http://localhost:8088/file
    billing: http://localhost:8086/billing


springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

---
spring:
  config:
    activate:
      on-profile: dev
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
