server:
  port: 8089
  servlet:
    context-path: /chat

spring:
  application:
    name: chat-service

  devtools:
    livereload:
      enabled: false

  cloud:
    openfeign:
      lazy-attributes-resolution: true
      client:
        config:
          identity-service:
            url: http://localhost:8080/identity
          profile-service:
            url: http://localhost:8082/profile
  data:
    mongodb:
      uri: mongodb://admin:${MONGO_PASSWORD:${MONGO_ROOT_PASSWORD:}}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/roomie_chat?authSource=admin
      auto-index-creation: true
    redis:
      host: ${REDIS_HOST:100.69.114.54}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

app:
  services:
    profile: http://localhost:8082/profile
    identity: http://localhost:8080/identity


springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

---
spring:
  config:
    activate:
      on-profile: dev
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
